### ISSUE TITLE
The Intercom API request failed with the code: 401

### ISSUE THREAD

**Issue by seyhunak** [intercom/intercom-rails#105]
Hello,

I'm using intercom-rails (0.2.27), when I try to import using rake test, getting this error below; doubled checked api key it is all correctly set on initializer. Can you re-produce this?

```
IntercomRails::IntercomAPIError: The Intercom API request failed with the code: 401, after 3 attempts.
```

**Comment by jamesbrooks** [comment]
+1 same issue here, will email eoin also.

**Comment by vinayr** [comment]
+1 having same issue

**Comment by vinayr** [comment]
https://github.com/intercom/intercom-rails/pull/114 should fix the issue.

**Comment by felixyz** [comment]
@vinayr I tried your patch but didn't solve the issue for me.
@eoin I've emailed you directly, any help would be much appreciated, but even better would be if we could determine what the problem is and resolve it.

**Comment by felixyz** [comment]
@eoin I dug around some more and uncovered two different problems:

1) There seems to be something wrong with the included certificate – authentication fails. The `intercom-ruby` gem uses a different cert (https://github.com/intercom/intercom-ruby/blob/master/lib/data/cacert.pem). Should we switch to that one?
2) When testing the request without authentication, I get the following response for each of my custom attributes:

`{"status":"bad_request","message":"bad 'days_left_of_trial' parameter"}`

Without custom attributes, it works (minus host verification).

Problem 1 seems to be easily fixable (switch the cert?), but for problem 2 it currently looks like a limitation with the bulk-import API?

**Comment by felixyz** [comment]
I should add I'm using `intercom-rails` 0.2.28. I think this issue should be re-opened. There's no reference to any PR or fix? @eoin

**Comment by felixyz** [comment]
It's unclear whether there are several problems manifesting in the same way. In any case, https://github.com/intercom/intercom-rails/pull/117 fixes the issue I identified: the `bad 'xyz' parameter` response.

The SSL cert issue seems to have been a red herring, perhaps some temporary problem. I didn't have to switch it to get things working.
